2019-12-10 00:26:06,011 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0de0f10a58>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:26:12,025 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb390>, 'Connection to 122.50.5.146 timed out. (connect timeout=5)')
2019-12-10 00:26:18,041 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb978>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:26:24,057 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ec5eb8>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 00:26:30,074 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb240>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 00:27:04,872 - __main__ - ERROR - Timeout Error
2019-12-10 00:27:21,814 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0f10ef0>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 00:27:27,831 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb470>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 00:27:33,847 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb080>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:27:39,864 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb320>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 00:28:01,846 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb898>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 00:28:19,996 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0de0ecb940>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:28:40,185 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ed6cc0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:29:10,718 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb0f0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:29:16,734 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ebb470>, 'Connection to 81.182.164.40 timed out. (connect timeout=5)')
2019-12-10 00:29:29,862 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ed6ef0>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:29:35,879 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f0de0ecb9b0>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 00:45:06,030 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7ff7f008e4a8>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 00:45:10,761 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7f008eb00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:45:40,282 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7f00a7940>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:45:46,298 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7ff7f008e7b8>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 00:46:35,921 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bdeac8>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 00:46:41,938 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa278>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:46:43,021 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c00b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:47:10,675 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfad68>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 00:47:11,757 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c00748>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:47:13,079 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2bfab00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:47:31,128 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 00:47:37,730 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c00240>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:47:43,746 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfad68>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 00:48:13,314 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2bfaf60>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:48:33,607 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00a20>, 'Connection to 81.182.164.40 timed out. (connect timeout=5)')
2019-12-10 00:49:16,402 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa898>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 00:49:22,419 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00ac8>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 00:49:37,322 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00630>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 00:49:38,633 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa898>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:49:57,201 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00a20>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 00:50:12,927 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2bfab00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:14,251 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c17ba8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:20,266 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c50d30>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 00:50:21,597 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c00668>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:27,611 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa4e0>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 00:50:39,094 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c170f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:40,446 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c004a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:50:49,891 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 00:50:55,907 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa828>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 00:51:10,898 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c2c17400>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:51:23,766 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00940>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 00:51:29,783 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c50dd8>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:51:47,526 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bfa208>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:52:12,305 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c004e0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 00:52:55,673 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00668>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 00:53:48,150 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c172e8>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:53:54,166 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2c00710>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 00:54:00,557 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 00:54:06,573 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa2c2bdef28>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:56:55,010 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fa613b0e518>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 00:57:14,379 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a540a58>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:57:25,419 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9908>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 00:57:30,434 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9358>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:57:35,448 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e96a0>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 00:57:40,463 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9b00>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 00:57:40,783 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503630>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:57:41,103 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:57:51,326 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9a20>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:57:56,340 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503dd8>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 00:58:04,615 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504ba8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:58:36,905 - __main__ - ERROR - Timeout Error
2019-12-10 00:59:07,886 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504710>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 00:59:08,194 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e96a0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:59:20,578 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503898>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 00:59:25,590 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504eb8>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 00:59:30,605 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503668>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 00:59:35,620 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540f28>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 00:59:35,702 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5040f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:59:36,021 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 00:59:48,342 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504cc0>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:00:01,474 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9a90>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:00:06,488 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540c88>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 01:00:11,504 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504b70>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:00:19,934 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9ac8>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:00:28,148 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540b38>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:00:33,162 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504fd0>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:00:58,300 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503860>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:00:58,384 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9438>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:01:03,400 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5045f8>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:01:25,494 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e95f8>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 01:01:30,508 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5034a8>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:01:35,866 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504630>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:01:40,878 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9898>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:01:45,892 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503c18>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:02:00,868 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504470>, 'Connection to 165.22.36.112 timed out. (connect timeout=5)')
2019-12-10 01:02:05,881 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5047f0>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:02:10,894 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503160>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:02:15,906 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504748>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 01:02:20,921 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9358>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:02:21,243 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a542e48>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:02:29,070 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504978>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:02:34,084 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9c50>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:02:57,438 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503518>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:03:02,454 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504e48>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:03:07,468 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9f60>, 'Connection to 81.182.164.40 timed out. (connect timeout=5)')
2019-12-10 01:03:13,998 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9da0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:03:17,881 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:03:22,890 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503160>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:04:05,339 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:04:10,354 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503710>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:04:29,771 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503a90>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:04:34,786 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9278>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:04:44,762 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504518>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:04:45,070 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:04:45,379 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a540d68>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:04:52,732 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e96d8>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:04:57,743 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504160>, 'Connection to 122.50.5.146 timed out. (connect timeout=5)')
2019-12-10 01:05:35,266 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503ba8>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:05:35,579 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e95c0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:05:40,593 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504080>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:05:50,852 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9908>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:05:55,867 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4955c0>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 01:05:56,183 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:06:01,197 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4952e8>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:06:06,210 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504c50>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:06:11,217 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4952b0>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:06:19,942 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9ba8>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:06:24,954 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a495e80>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 01:06:44,538 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503898>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 01:07:04,566 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 01:07:04,901 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5037b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:07:28,174 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9f60>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:07:51,790 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504780>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 01:07:59,470 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9f98>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:08:04,484 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503438>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:08:09,498 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e97f0>, 'Connection to 81.182.164.40 timed out. (connect timeout=5)')
2019-12-10 01:08:14,511 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503d30>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:08:19,526 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504cc0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:08:29,568 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9fd0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:08:34,583 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504898>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:08:39,599 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5030f0>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:08:47,372 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9a20>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:08:59,566 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a540da0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:09:18,944 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a542358>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:09:23,958 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504630>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:10:02,360 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503550>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:10:02,441 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504470>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:10:46,446 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503cc0>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:10:51,458 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9358>, 'Connection to 36.78.76.9 timed out. (connect timeout=5)')
2019-12-10 01:10:56,471 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504b00>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:11:05,277 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503f98>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:11:10,292 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504400>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:11:15,306 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503c18>, 'Connection to 183.89.62.87 timed out. (connect timeout=5)')
2019-12-10 01:11:20,322 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504c18>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:11:27,089 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:11:32,098 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5044a8>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:11:42,772 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5038d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:11:47,778 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5047b8>, 'Connection to 122.50.5.146 timed out. (connect timeout=5)')
2019-12-10 01:11:52,793 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503828>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:12:33,639 - __main__ - ERROR - Timeout Error
2019-12-10 01:12:44,293 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504c18>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:12:54,798 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503080>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:12:59,813 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5409e8>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:13:04,826 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5037b8>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:13:15,002 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9470>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:13:55,149 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504828>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:13:57,971 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:14:23,654 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503d30>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:14:32,613 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9828>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:14:54,093 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504be0>, 'Connection to 81.182.164.40 timed out. (connect timeout=5)')
2019-12-10 01:14:56,821 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503438>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:15:10,292 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5046a0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:15:29,223 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:15:34,239 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9898>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:15:50,298 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540f28>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:16:07,565 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503ef0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:16:19,844 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5025f8>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:16:20,160 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9320>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:16:50,399 - __main__ - ERROR - Timeout Error
2019-12-10 01:16:57,755 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503cf8>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:17:07,370 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504748>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:17:14,722 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540c50>, 'Connection to 165.22.36.112 timed out. (connect timeout=5)')
2019-12-10 01:17:39,554 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a502ac8>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:17:39,868 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9ef0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:18:12,064 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504080>, 'Connection to 36.78.76.9 timed out. (connect timeout=5)')
2019-12-10 01:18:17,074 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503b00>, 'Connection to 36.78.76.9 timed out. (connect timeout=5)')
2019-12-10 01:18:22,089 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a502278>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:18:27,104 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9e48>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:18:42,934 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a502e80>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 01:18:52,874 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504358>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:19:48,361 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a540eb8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:19:53,374 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9278>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:20:02,638 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5022b0>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:20:12,594 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504860>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 01:20:42,839 - __main__ - ERROR - Timeout Error
2019-12-10 01:20:47,851 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9cc0>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:20:48,151 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a540c88>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:20:53,161 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5036d8>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:20:53,480 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503518>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:21:04,278 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504908>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:21:06,958 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9390>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:21:11,970 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5024e0>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:21:16,776 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:21:32,366 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503fd0>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 01:21:37,323 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9cf8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:21:44,460 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9390>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:22:03,833 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504828>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:22:13,504 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540f98>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:22:18,518 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503ef0>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:22:43,798 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 01:22:43,877 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9780>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:23:07,014 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503cf8>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:23:12,029 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a502eb8>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:23:17,045 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503eb8>, 'Connection to 183.89.62.87 timed out. (connect timeout=5)')
2019-12-10 01:23:17,127 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:23:51,467 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5046d8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:24:06,411 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503550>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 01:24:06,492 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503b70>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:24:11,790 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5422b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:24:16,805 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504908>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 01:24:21,820 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9278>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:24:21,902 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a542dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:24:26,917 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504390>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:24:31,930 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5033c8>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:24:39,378 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a542ba8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:24:44,390 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a542d68>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 01:24:44,694 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:24:49,706 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504c50>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:24:54,718 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9320>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:24:59,729 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9908>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:25:00,047 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:25:10,370 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503940>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:25:16,613 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503e48>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:25:21,626 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540a58>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:25:40,516 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5032b0>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:25:47,901 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503390>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:25:58,642 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9860>, 'Connection to 183.89.62.87 timed out. (connect timeout=5)')
2019-12-10 01:26:03,659 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb668>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:26:08,674 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5047f0>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 01:26:20,510 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:26:25,522 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb9e8>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 01:26:50,509 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 01:27:09,108 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a542d68>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:27:24,394 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb7b8>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:28:02,678 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:28:02,756 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9320>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:28:19,230 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9da0>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:28:36,073 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb5c0>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:28:41,088 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503b00>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 01:28:41,382 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504240>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:28:46,398 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e92b0>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:29:13,606 - __main__ - ERROR - Timeout Error
2019-12-10 01:29:18,618 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503e10>, 'Connection to 41.180.64.254 timed out. (connect timeout=5)')
2019-12-10 01:29:23,630 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb588>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:29:23,713 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb748>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:29:28,726 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5049e8>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:29:37,990 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e91d0>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:29:43,005 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503438>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:29:43,322 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb438>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:29:45,904 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a542358>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:30:19,762 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9d68>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:30:31,530 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503da0>, 'Connection to 165.22.36.112 timed out. (connect timeout=5)')
2019-12-10 01:30:48,822 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5035f8>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:30:49,111 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:30:57,784 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503438>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:31:02,798 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4cb6a0>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 01:31:07,814 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e91d0>, 'Connection to 165.22.36.112 timed out. (connect timeout=5)')
2019-12-10 01:31:12,826 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504e80>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:31:35,292 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5030b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:31:43,758 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504160>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:31:48,770 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a542940>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 01:32:10,786 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504cc0>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:32:15,796 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5034e0>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:32:26,371 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5031d0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:32:31,387 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540e48>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:33:21,009 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a500588>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:33:23,156 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:33:28,713 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504ef0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:33:36,063 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540e80>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:33:48,259 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503cf8>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:33:48,576 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a500518>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:33:58,572 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504438>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:34:13,155 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5047f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:34:18,162 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9780>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:34:23,170 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500f98>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 01:34:28,185 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503ef0>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:34:48,540 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9940>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:34:55,858 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5041d0>, 'Connection to 183.89.62.87 timed out. (connect timeout=5)')
2019-12-10 01:35:23,090 - __main__ - ERROR - Timeout Error
2019-12-10 01:35:30,442 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5409e8>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:35:37,394 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a542cc0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:35:47,345 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:35:52,360 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540c50>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:35:57,375 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9550>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:36:03,225 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5004a8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:36:08,240 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5031d0>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:36:35,471 - __main__ - ERROR - Timeout Error
2019-12-10 01:36:48,356 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500b00>, 'Connection to 183.89.62.87 timed out. (connect timeout=5)')
2019-12-10 01:37:07,217 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a542940>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:37:12,230 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503208>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:37:24,134 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5045f8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:37:29,142 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9518>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:38:11,162 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a540f28>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:38:16,177 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504828>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:38:35,778 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9400>, 'Connection to 183.89.62.87 timed out. (connect timeout=5)')
2019-12-10 01:38:36,095 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5039b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:38:45,703 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a542c18>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:38:50,719 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504cf8>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:39:01,825 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503e10>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 01:39:22,179 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9710>, 'Connection to 122.50.5.146 timed out. (connect timeout=5)')
2019-12-10 01:39:50,500 - __main__ - ERROR - Timeout Error
2019-12-10 01:40:08,539 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 01:40:28,176 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e93c8>, 'Connection to 183.89.62.87 timed out. (connect timeout=5)')
2019-12-10 01:40:33,190 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503da0>, 'Connection to 41.180.64.254 timed out. (connect timeout=5)')
2019-12-10 01:40:38,202 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9080>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:40:38,487 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a500a90>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:40:43,502 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9860>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 01:40:48,516 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500128>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:40:52,445 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:40:57,458 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5002e8>, 'Connection to 122.50.5.146 timed out. (connect timeout=5)')
2019-12-10 01:41:02,474 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5039e8>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:41:07,486 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503320>, 'Connection to 94.51.83.2 timed out. (connect timeout=5)')
2019-12-10 01:41:07,802 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e95f8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:41:12,814 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504eb8>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 01:41:13,089 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a500780>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:41:57,914 - __main__ - ERROR - Timeout Error
2019-12-10 01:42:33,662 - __main__ - ERROR - Timeout Error
2019-12-10 01:42:33,745 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a500518>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:42:38,758 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e92b0>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:42:47,295 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540f28>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:43:04,963 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5038d0>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:43:09,977 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500ba8>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:43:10,058 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9e48>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:43:10,375 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504668>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:43:15,385 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540cf8>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:43:26,022 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a500b00>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:43:31,037 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5038d0>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:43:31,305 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9e10>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:43:45,410 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504cc0>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:43:50,424 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e92e8>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:43:55,440 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503320>, 'Connection to 213.109.129.56 timed out. (connect timeout=5)')
2019-12-10 01:44:07,873 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:44:12,702 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e98d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:44:26,946 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9390>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:44:35,953 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540d68>, 'Connection to 109.251.185.20 timed out. (connect timeout=5)')
2019-12-10 01:44:40,968 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9e10>, 'Connection to 165.22.36.112 timed out. (connect timeout=5)')
2019-12-10 01:44:41,280 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5037b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:44:53,447 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:45:03,450 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5429e8>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:45:08,466 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500b00>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:45:24,382 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503a58>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:45:36,875 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9ef0>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 01:45:42,127 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 01:45:42,446 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9e80>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:45:58,438 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503f60>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:46:01,078 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503ac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:46:18,251 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9860>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:46:49,010 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5049e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:47:19,257 - __main__ - ERROR - Timeout Error
2019-12-10 01:47:24,270 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503e48>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:47:29,286 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e90b8>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:47:34,300 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5000f0>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:47:43,319 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503198>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:47:54,899 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5000f0>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:47:55,220 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a5047f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:47:55,536 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503470>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:48:06,994 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504518>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:48:07,274 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a503c88>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:48:12,285 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500cc0>, 'Connection to 81.17.150.122 timed out. (connect timeout=5)')
2019-12-10 01:48:17,219 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 01:48:29,846 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a542c88>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 01:48:29,929 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a504438>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:48:34,942 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a540cf8>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:48:58,881 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5031d0>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:49:11,141 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5007f0>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:49:16,155 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9f98>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:49:21,166 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504048>, 'Connection to 36.78.76.9 timed out. (connect timeout=5)')
2019-12-10 01:49:26,181 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9080>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 01:49:37,484 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5040f0>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 01:49:41,517 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 01:49:46,533 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500278>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:49:56,931 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5007f0>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 01:49:57,012 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e99b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:50:02,026 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500d68>, 'Connection to 183.89.62.87 timed out. (connect timeout=5)')
2019-12-10 01:50:29,242 - __main__ - ERROR - Timeout Error
2019-12-10 01:50:34,254 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504588>, 'Connection to 182.52.238.118 timed out. (connect timeout=5)')
2019-12-10 01:50:56,682 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500198>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:51:01,696 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9160>, 'Connection to 110.77.231.80 timed out. (connect timeout=5)')
2019-12-10 01:51:06,712 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5429e8>, 'Connection to 177.21.224.73 timed out. (connect timeout=5)')
2019-12-10 01:51:11,728 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500b70>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:51:16,743 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503518>, 'Connection to 91.237.3.59 timed out. (connect timeout=5)')
2019-12-10 01:51:32,734 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9438>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 01:51:33,052 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a542940>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:51:41,978 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a4e98d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 01:51:48,954 - __main__ - ERROR - ('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))
2019-12-10 01:51:59,386 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a500978>, 'Connection to 103.86.135.42 timed out. (connect timeout=5)')
2019-12-10 01:52:04,399 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503278>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 01:52:05,862 - __name__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f471a859630>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 02:01:47,543 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5049b0>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 02:01:52,553 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a5005f8>, 'Connection to 185.58.16.41 timed out. (connect timeout=5)')
2019-12-10 02:01:57,381 - __main__ - ERROR - ('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a9a500b38>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-12-10 02:02:02,390 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503518>, 'Connection to 59.100.172.214 timed out. (connect timeout=5)')
2019-12-10 02:02:14,209 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a504e10>, 'Connection to 180.246.175.240 timed out. (connect timeout=5)')
2019-12-10 02:02:20,477 - __main__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
2019-12-10 02:02:25,489 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9b38>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 02:02:32,640 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a503048>, 'Connection to 36.92.213.45 timed out. (connect timeout=5)')
2019-12-10 02:02:37,651 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a542ac8>, 'Connection to 36.78.76.9 timed out. (connect timeout=5)')
2019-12-10 02:02:42,663 - __main__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7f2a9a4e9d30>, 'Connection to 177.220.188.213 timed out. (connect timeout=5)')
2019-12-10 02:11:48,404 - __name__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fd2ee3bfc88>, 'Connection to 195.78.112.235 timed out. (connect timeout=5)')
2019-12-10 02:12:30,440 - __name__ - ERROR - (<urllib3.connection.HTTPConnection object at 0x7fea9af1ecf8>, 'Connection to 165.22.36.112 timed out. (connect timeout=5)')
2019-12-10 02:18:28,160 - __name__ - ERROR - ('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer'))
